import type {
  ComplianceGap,
  OfficeMetrics,
  PendingAction,
  PredefinedReport,
  ReportFieldDefinition,
  ReportRow,
  SavedQuery,
  ScheduledReport,
} from '../types'

export const FIELD_OFFICES = [
  'All Offices',
  'Las Vegas',
  'Boulder',
  'Mountain View',
  'Austin',
  'Philadelphia',
] as const

export type FieldOffice = (typeof FIELD_OFFICES)[number]

export const CHART_COLORS = {
  primary: 'var(--color-chart-1)',
  secondary: 'var(--color-chart-2)',
  accent: 'var(--color-chart-3)',
  muted: 'var(--color-chart-4)',
  highlight: 'var(--color-chart-5)',
  series1: 'var(--color-chart-1)',
  series2: 'var(--color-chart-2)',
  series3: 'var(--color-chart-3)',
  series4: 'var(--color-chart-4)',
  series5: 'var(--color-chart-5)',
} as const

export const OFFICE_DATA: Record<string, OfficeMetrics> = {
  "All Offices": {
    totalAssets: 1006,
    totalValue: "$1.95M",
    pendingCount: 45,
    assetValueByLocation: [
      { name: "HQ Floor 1", value: 450000, count: 234 },
      { name: "HQ Floor 2", value: 380000, count: 198 },
      { name: "HQ Floor 3", value: 520000, count: 267 },
      { name: "Branch Office A", value: 290000, count: 145 },
      { name: "Branch Office B", value: 310000, count: 162 },
    ],
    lifecycleBreakdown: [
      { name: "Registered", value: 45, percentage: 4.5 },
      { name: "In Use", value: 756, percentage: 75.6 },
      { name: "Available", value: 52, percentage: 5.2 },
      {
        name: "Under Verification",
        value: 28,
        percentage: 2.8,
      },
      { name: "Transferred", value: 34, percentage: 3.4 },
      { name: "Damaged", value: 15, percentage: 1.5 },
      { name: "Retired", value: 50, percentage: 5.0 },
      { name: "Disposed", value: 20, percentage: 2.0 },
    ],
    monthlyTrends: [
      {
        month: "Jan",
        acquisitions: 45,
        disposals: 12,
        transfers: 34,
      },
      {
        month: "Feb",
        acquisitions: 52,
        disposals: 8,
        transfers: 41,
      },
      {
        month: "Mar",
        acquisitions: 38,
        disposals: 15,
        transfers: 38,
      },
      {
        month: "Apr",
        acquisitions: 61,
        disposals: 10,
        transfers: 52,
      },
      {
        month: "May",
        acquisitions: 55,
        disposals: 18,
        transfers: 45,
      },
      {
        month: "Jun",
        acquisitions: 48,
        disposals: 14,
        transfers: 39,
      },
    ],
    surveyCaseVolume: [
      { month: "Jan", opened: 8, completed: 6, inProgress: 2 },
      {
        month: "Feb",
        opened: 12,
        completed: 10,
        inProgress: 4,
      },
      { month: "Mar", opened: 6, completed: 8, inProgress: 2 },
      {
        month: "Apr",
        opened: 15,
        completed: 11,
        inProgress: 6,
      },
      { month: "May", opened: 9, completed: 12, inProgress: 3 },
      { month: "Jun", opened: 11, completed: 7, inProgress: 7 },
    ],
    disposalTrends: [
      {
        month: "Jan",
        auction: 3,
        donation: 2,
        recycling: 4,
        writeOff: 3,
      },
      {
        month: "Feb",
        auction: 1,
        donation: 1,
        recycling: 3,
        writeOff: 3,
      },
      {
        month: "Mar",
        auction: 4,
        donation: 3,
        recycling: 5,
        writeOff: 3,
      },
      {
        month: "Apr",
        auction: 2,
        donation: 1,
        recycling: 2,
        writeOff: 5,
      },
      {
        month: "May",
        auction: 5,
        donation: 4,
        recycling: 3,
        writeOff: 6,
      },
      {
        month: "Jun",
        auction: 3,
        donation: 2,
        recycling: 4,
        writeOff: 5,
      },
    ],
    complianceGaps: [
      { type: "Missing Serial Numbers", count: 23 },
      { type: "Untagged Assets", count: 12 },
      { type: "Overdue Inspection", count: 45 },
      { type: "Missing Custodian", count: 8 },
      { type: "Incomplete Documentation", count: 34 },
    ],
  },
  "Las Vegas": {
    totalAssets: 218,
    totalValue: "$420K",
    pendingCount: 9,
    assetValueByLocation: [
      { name: "LV Floor 1", value: 180000, count: 95 },
      { name: "LV Floor 2", value: 140000, count: 78 },
      { name: "LV Warehouse", value: 100000, count: 45 },
    ],
    lifecycleBreakdown: [
      { name: "Registered", value: 10, percentage: 4.6 },
      { name: "In Use", value: 162, percentage: 74.3 },
      { name: "Available", value: 14, percentage: 6.4 },
      { name: "Under Verification", value: 6, percentage: 2.8 },
      { name: "Transferred", value: 8, percentage: 3.7 },
      { name: "Damaged", value: 4, percentage: 1.8 },
      { name: "Retired", value: 10, percentage: 4.6 },
      { name: "Disposed", value: 4, percentage: 1.8 },
    ],
    monthlyTrends: [
      {
        month: "Jan",
        acquisitions: 10,
        disposals: 2,
        transfers: 7,
      },
      {
        month: "Feb",
        acquisitions: 12,
        disposals: 1,
        transfers: 9,
      },
      {
        month: "Mar",
        acquisitions: 8,
        disposals: 3,
        transfers: 8,
      },
      {
        month: "Apr",
        acquisitions: 14,
        disposals: 2,
        transfers: 11,
      },
      {
        month: "May",
        acquisitions: 11,
        disposals: 4,
        transfers: 9,
      },
      {
        month: "Jun",
        acquisitions: 9,
        disposals: 3,
        transfers: 7,
      },
    ],
    surveyCaseVolume: [
      { month: "Jan", opened: 2, completed: 1, inProgress: 1 },
      { month: "Feb", opened: 3, completed: 2, inProgress: 1 },
      { month: "Mar", opened: 1, completed: 2, inProgress: 0 },
      { month: "Apr", opened: 4, completed: 3, inProgress: 1 },
      { month: "May", opened: 2, completed: 3, inProgress: 1 },
      { month: "Jun", opened: 3, completed: 1, inProgress: 2 },
    ],
    disposalTrends: [
      {
        month: "Jan",
        auction: 1,
        donation: 0,
        recycling: 1,
        writeOff: 0,
      },
      {
        month: "Feb",
        auction: 0,
        donation: 0,
        recycling: 1,
        writeOff: 0,
      },
      {
        month: "Mar",
        auction: 1,
        donation: 1,
        recycling: 1,
        writeOff: 0,
      },
      {
        month: "Apr",
        auction: 0,
        donation: 0,
        recycling: 1,
        writeOff: 1,
      },
      {
        month: "May",
        auction: 1,
        donation: 1,
        recycling: 1,
        writeOff: 1,
      },
      {
        month: "Jun",
        auction: 1,
        donation: 0,
        recycling: 1,
        writeOff: 1,
      },
    ],
    complianceGaps: [
      { type: "Missing Serial Numbers", count: 5 },
      { type: "Untagged Assets", count: 3 },
      { type: "Overdue Inspection", count: 9 },
      { type: "Missing Custodian", count: 2 },
      { type: "Incomplete Documentation", count: 7 },
    ],
  },
  Boulder: {
    totalAssets: 187,
    totalValue: "$360K",
    pendingCount: 7,
    assetValueByLocation: [
      { name: "Boulder Main", value: 210000, count: 110 },
      { name: "Boulder Annex", value: 150000, count: 77 },
    ],
    lifecycleBreakdown: [
      { name: "Registered", value: 8, percentage: 4.3 },
      { name: "In Use", value: 143, percentage: 76.5 },
      { name: "Available", value: 10, percentage: 5.3 },
      { name: "Under Verification", value: 5, percentage: 2.7 },
      { name: "Transferred", value: 7, percentage: 3.7 },
      { name: "Damaged", value: 3, percentage: 1.6 },
      { name: "Retired", value: 9, percentage: 4.8 },
      { name: "Disposed", value: 2, percentage: 1.1 },
    ],
    monthlyTrends: [
      {
        month: "Jan",
        acquisitions: 8,
        disposals: 2,
        transfers: 6,
      },
      {
        month: "Feb",
        acquisitions: 10,
        disposals: 1,
        transfers: 8,
      },
      {
        month: "Mar",
        acquisitions: 7,
        disposals: 3,
        transfers: 7,
      },
      {
        month: "Apr",
        acquisitions: 12,
        disposals: 2,
        transfers: 10,
      },
      {
        month: "May",
        acquisitions: 9,
        disposals: 4,
        transfers: 8,
      },
      {
        month: "Jun",
        acquisitions: 8,
        disposals: 2,
        transfers: 6,
      },
    ],
    surveyCaseVolume: [
      { month: "Jan", opened: 1, completed: 1, inProgress: 0 },
      { month: "Feb", opened: 2, completed: 2, inProgress: 1 },
      { month: "Mar", opened: 1, completed: 1, inProgress: 0 },
      { month: "Apr", opened: 3, completed: 2, inProgress: 1 },
      { month: "May", opened: 2, completed: 2, inProgress: 1 },
      { month: "Jun", opened: 2, completed: 1, inProgress: 2 },
    ],
    disposalTrends: [
      {
        month: "Jan",
        auction: 0,
        donation: 1,
        recycling: 1,
        writeOff: 0,
      },
      {
        month: "Feb",
        auction: 0,
        donation: 0,
        recycling: 1,
        writeOff: 0,
      },
      {
        month: "Mar",
        auction: 1,
        donation: 1,
        recycling: 1,
        writeOff: 1,
      },
      {
        month: "Apr",
        auction: 0,
        donation: 0,
        recycling: 0,
        writeOff: 1,
      },
      {
        month: "May",
        auction: 1,
        donation: 1,
        recycling: 1,
        writeOff: 1,
      },
      {
        month: "Jun",
        auction: 0,
        donation: 1,
        recycling: 1,
        writeOff: 0,
      },
    ],
    complianceGaps: [
      { type: "Missing Serial Numbers", count: 4 },
      { type: "Untagged Assets", count: 2 },
      { type: "Overdue Inspection", count: 8 },
      { type: "Missing Custodian", count: 1 },
      { type: "Incomplete Documentation", count: 6 },
    ],
  },
  "Mountain View": {
    totalAssets: 245,
    totalValue: "$510K",
    pendingCount: 12,
    assetValueByLocation: [
      { name: "MV Campus A", value: 260000, count: 130 },
      { name: "MV Campus B", value: 180000, count: 90 },
      { name: "MV Lab", value: 70000, count: 25 },
    ],
    lifecycleBreakdown: [
      { name: "Registered", value: 12, percentage: 4.9 },
      { name: "In Use", value: 185, percentage: 75.5 },
      { name: "Available", value: 14, percentage: 5.7 },
      { name: "Under Verification", value: 7, percentage: 2.9 },
      { name: "Transferred", value: 9, percentage: 3.7 },
      { name: "Damaged", value: 4, percentage: 1.6 },
      { name: "Retired", value: 11, percentage: 4.5 },
      { name: "Disposed", value: 3, percentage: 1.2 },
    ],
    monthlyTrends: [
      {
        month: "Jan",
        acquisitions: 12,
        disposals: 3,
        transfers: 9,
      },
      {
        month: "Feb",
        acquisitions: 14,
        disposals: 2,
        transfers: 11,
      },
      {
        month: "Mar",
        acquisitions: 10,
        disposals: 4,
        transfers: 10,
      },
      {
        month: "Apr",
        acquisitions: 16,
        disposals: 3,
        transfers: 14,
      },
      {
        month: "May",
        acquisitions: 14,
        disposals: 5,
        transfers: 12,
      },
      {
        month: "Jun",
        acquisitions: 12,
        disposals: 4,
        transfers: 10,
      },
    ],
    surveyCaseVolume: [
      { month: "Jan", opened: 2, completed: 2, inProgress: 0 },
      { month: "Feb", opened: 3, completed: 3, inProgress: 1 },
      { month: "Mar", opened: 2, completed: 2, inProgress: 1 },
      { month: "Apr", opened: 4, completed: 3, inProgress: 2 },
      { month: "May", opened: 2, completed: 3, inProgress: 1 },
      { month: "Jun", opened: 3, completed: 2, inProgress: 2 },
    ],
    disposalTrends: [
      {
        month: "Jan",
        auction: 1,
        donation: 1,
        recycling: 1,
        writeOff: 0,
      },
      {
        month: "Feb",
        auction: 0,
        donation: 0,
        recycling: 1,
        writeOff: 1,
      },
      {
        month: "Mar",
        auction: 1,
        donation: 1,
        recycling: 2,
        writeOff: 0,
      },
      {
        month: "Apr",
        auction: 1,
        donation: 0,
        recycling: 1,
        writeOff: 1,
      },
      {
        month: "May",
        auction: 2,
        donation: 1,
        recycling: 1,
        writeOff: 1,
      },
      {
        month: "Jun",
        auction: 1,
        donation: 1,
        recycling: 1,
        writeOff: 1,
      },
    ],
    complianceGaps: [
      { type: "Missing Serial Numbers", count: 6 },
      { type: "Untagged Assets", count: 3 },
      { type: "Overdue Inspection", count: 12 },
      { type: "Missing Custodian", count: 2 },
      { type: "Incomplete Documentation", count: 9 },
    ],
  },
  Austin: {
    totalAssets: 196,
    totalValue: "$375K",
    pendingCount: 8,
    assetValueByLocation: [
      { name: "Austin HQ", value: 220000, count: 115 },
      { name: "Austin South", value: 155000, count: 81 },
    ],
    lifecycleBreakdown: [
      { name: "Registered", value: 9, percentage: 4.6 },
      { name: "In Use", value: 149, percentage: 76.0 },
      { name: "Available", value: 11, percentage: 5.6 },
      { name: "Under Verification", value: 5, percentage: 2.6 },
      { name: "Transferred", value: 7, percentage: 3.6 },
      { name: "Damaged", value: 3, percentage: 1.5 },
      { name: "Retired", value: 9, percentage: 4.6 },
      { name: "Disposed", value: 3, percentage: 1.5 },
    ],
    monthlyTrends: [
      {
        month: "Jan",
        acquisitions: 9,
        disposals: 2,
        transfers: 7,
      },
      {
        month: "Feb",
        acquisitions: 11,
        disposals: 2,
        transfers: 8,
      },
      {
        month: "Mar",
        acquisitions: 8,
        disposals: 3,
        transfers: 7,
      },
      {
        month: "Apr",
        acquisitions: 13,
        disposals: 2,
        transfers: 11,
      },
      {
        month: "May",
        acquisitions: 11,
        disposals: 3,
        transfers: 9,
      },
      {
        month: "Jun",
        acquisitions: 10,
        disposals: 3,
        transfers: 8,
      },
    ],
    surveyCaseVolume: [
      { month: "Jan", opened: 2, completed: 1, inProgress: 1 },
      { month: "Feb", opened: 2, completed: 2, inProgress: 1 },
      { month: "Mar", opened: 1, completed: 2, inProgress: 0 },
      { month: "Apr", opened: 3, completed: 2, inProgress: 1 },
      { month: "May", opened: 2, completed: 2, inProgress: 1 },
      { month: "Jun", opened: 2, completed: 2, inProgress: 1 },
    ],
    disposalTrends: [
      {
        month: "Jan",
        auction: 0,
        donation: 1,
        recycling: 1,
        writeOff: 0,
      },
      {
        month: "Feb",
        auction: 1,
        donation: 0,
        recycling: 1,
        writeOff: 0,
      },
      {
        month: "Mar",
        auction: 1,
        donation: 0,
        recycling: 1,
        writeOff: 1,
      },
      {
        month: "Apr",
        auction: 0,
        donation: 1,
        recycling: 0,
        writeOff: 1,
      },
      {
        month: "May",
        auction: 1,
        donation: 1,
        recycling: 1,
        writeOff: 0,
      },
      {
        month: "Jun",
        auction: 0,
        donation: 0,
        recycling: 1,
        writeOff: 1,
      },
    ],
    complianceGaps: [
      { type: "Missing Serial Numbers", count: 4 },
      { type: "Untagged Assets", count: 2 },
      { type: "Overdue Inspection", count: 7 },
      { type: "Missing Custodian", count: 1 },
      { type: "Incomplete Documentation", count: 6 },
    ],
  },
  Philadelphia: {
    totalAssets: 160,
    totalValue: "$285K",
    pendingCount: 9,
    assetValueByLocation: [
      { name: "Philly Downtown", value: 165000, count: 88 },
      { name: "Philly North", value: 120000, count: 72 },
    ],
    lifecycleBreakdown: [
      { name: "Registered", value: 6, percentage: 3.8 },
      { name: "In Use", value: 117, percentage: 73.1 },
      { name: "Available", value: 9, percentage: 5.6 },
      { name: "Under Verification", value: 5, percentage: 3.1 },
      { name: "Transferred", value: 5, percentage: 3.1 },
      { name: "Damaged", value: 4, percentage: 2.5 },
      { name: "Retired", value: 11, percentage: 6.9 },
      { name: "Disposed", value: 3, percentage: 1.9 },
    ],
    monthlyTrends: [
      {
        month: "Jan",
        acquisitions: 7,
        disposals: 2,
        transfers: 5,
      },
      {
        month: "Feb",
        acquisitions: 8,
        disposals: 2,
        transfers: 6,
      },
      {
        month: "Mar",
        acquisitions: 6,
        disposals: 3,
        transfers: 5,
      },
      {
        month: "Apr",
        acquisitions: 10,
        disposals: 1,
        transfers: 8,
      },
      {
        month: "May",
        acquisitions: 9,
        disposals: 3,
        transfers: 7,
      },
      {
        month: "Jun",
        acquisitions: 7,
        disposals: 2,
        transfers: 6,
      },
    ],
    surveyCaseVolume: [
      { month: "Jan", opened: 1, completed: 1, inProgress: 0 },
      { month: "Feb", opened: 2, completed: 1, inProgress: 1 },
      { month: "Mar", opened: 1, completed: 1, inProgress: 1 },
      { month: "Apr", opened: 2, completed: 1, inProgress: 2 },
      { month: "May", opened: 1, completed: 2, inProgress: 0 },
      { month: "Jun", opened: 2, completed: 1, inProgress: 1 },
    ],
    disposalTrends: [
      {
        month: "Jan",
        auction: 1,
        donation: 0,
        recycling: 0,
        writeOff: 1,
      },
      {
        month: "Feb",
        auction: 0,
        donation: 1,
        recycling: 0,
        writeOff: 1,
      },
      {
        month: "Mar",
        auction: 1,
        donation: 0,
        recycling: 1,
        writeOff: 1,
      },
      {
        month: "Apr",
        auction: 1,
        donation: 0,
        recycling: 1,
        writeOff: 1,
      },
      {
        month: "May",
        auction: 0,
        donation: 1,
        recycling: 1,
        writeOff: 2,
      },
      {
        month: "Jun",
        auction: 1,
        donation: 0,
        recycling: 1,
        writeOff: 1,
      },
    ],
    complianceGaps: [
      { type: "Missing Serial Numbers", count: 4 },
      { type: "Untagged Assets", count: 2 },
      { type: "Overdue Inspection", count: 9 },
      { type: "Missing Custodian", count: 2 },
      { type: "Incomplete Documentation", count: 6 },
    ],
  },
};

export const ALL_PENDING_ACTIONS: PendingAction[] = [
  {
    id: "PA-001",
    type: "inspection",
    description: "Quarterly inspection overdue for IT assets",
    assetCount: 18,
    dueDate: "2026-02-15",
    assignedTo: "John Smith",
    fieldOffice: "Las Vegas",
  },
  {
    id: "PA-002",
    type: "disposal",
    description:
      "Pending disposal approval for retired equipment",
    assetCount: 7,
    dueDate: "2026-03-01",
    assignedTo: "Sarah Johnson",
    fieldOffice: "Boulder",
  },
  {
    id: "PA-003",
    type: "tagging",
    description:
      "RFID tags not assigned to newly registered assets",
    assetCount: 12,
    dueDate: "2026-03-05",
    assignedTo: "Mike Chen",
    fieldOffice: "Mountain View",
  },
  {
    id: "PA-004",
    type: "transfer",
    description:
      "Pending transfer acknowledgments from Branch B",
    assetCount: 5,
    dueDate: "2026-03-10",
    assignedTo: "Lisa Wong",
    fieldOffice: "Austin",
  },
  {
    id: "PA-005",
    type: "verification",
    description: "Post-transfer verification incomplete",
    assetCount: 3,
    dueDate: "2026-03-15",
    assignedTo: "David Park",
    fieldOffice: "Philadelphia",
  },
];

export const MOCK_REPORT_DATA: ReportRow[] = [
    {
      assetId: "A-001",
      name: "Dell Laptop XPS 15",
      category: "IT Equipment",
      serialNumber: "DL-2024-001",
      location: "HQ Floor 1",
      fieldOffice: "Headquarters",
      custodian: "John Smith",
      status: "In Use",
      condition: "Good",
      value: "$1,200",
      nbv: "$800",
      purchaseDate: "2024-01-10",
      poNumber: "PO-2024-001",
      supplier: "Dell Inc.",
      lastInspection: "2026-01-15",
    },
    {
      assetId: "A-002",
      name: "HP LaserJet Printer",
      category: "Office Equipment",
      serialNumber: "HP-2023-045",
      location: "HQ Floor 2",
      fieldOffice: "Headquarters",
      custodian: "Sarah Johnson",
      status: "In Use",
      condition: "Good",
      value: "$450",
      nbv: "$200",
      purchaseDate: "2023-06-20",
      poNumber: "PO-2023-012",
      supplier: "HP Inc.",
      lastInspection: "2026-01-20",
    },
    {
      assetId: "A-003",
      name: "Cisco Switch 48-Port",
      category: "IT Equipment",
      serialNumber: "CS-2023-112",
      location: "HQ Floor 3",
      fieldOffice: "Headquarters",
      custodian: "Mike Chen",
      status: "Under Verification",
      condition: "Fair",
      value: "$3,800",
      nbv: "$2,100",
      purchaseDate: "2023-03-15",
      poNumber: "PO-2023-005",
      supplier: "Cisco Systems",
      lastInspection: "2025-12-10",
    },
    {
      assetId: "A-004",
      name: "Standing Desk",
      category: "Furniture",
      serialNumber: "SD-2024-023",
      location: "Branch Office A",
      fieldOffice: "Branch A",
      custodian: "Lisa Wong",
      status: "In Use",
      condition: "Good",
      value: "$650",
      nbv: "$500",
      purchaseDate: "2024-02-01",
      poNumber: "PO-2024-003",
      supplier: "ErgoDesk",
      lastInspection: "2026-02-01",
    },
    {
      assetId: "A-005",
      name: "Projector Epson",
      category: "Office Equipment",
      serialNumber: "EP-2022-078",
      location: "Branch Office B",
      fieldOffice: "Branch B",
      custodian: "David Park",
      status: "Damaged",
      condition: "Poor",
      value: "$800",
      nbv: "$150",
      purchaseDate: "2022-09-10",
      poNumber: "PO-2022-018",
      supplier: "Epson",
      lastInspection: "2025-11-05",
    },
    {
      assetId: "A-006",
      name: 'MacBook Pro 14"',
      category: "IT Equipment",
      serialNumber: "AP-2024-089",
      location: "HQ Floor 1",
      fieldOffice: "Headquarters",
      custodian: "Anna Lee",
      status: "In Use",
      condition: "Excellent",
      value: "$2,400",
      nbv: "$2,000",
      purchaseDate: "2024-05-01",
      poNumber: "PO-2024-010",
      supplier: "Apple Inc.",
      lastInspection: "2026-02-10",
    },
    {
      assetId: "A-007",
      name: "Office Chair Herman Miller",
      category: "Furniture",
      serialNumber: "HM-2023-034",
      location: "HQ Floor 2",
      fieldOffice: "Headquarters",
      custodian: "Tom Wilson",
      status: "Retired",
      condition: "Poor",
      value: "$950",
      nbv: "$0",
      purchaseDate: "2020-04-15",
      poNumber: "PO-2020-007",
      supplier: "Herman Miller",
      lastInspection: "2025-10-20",
    },
    {
      assetId: "A-008",
      name: "UPS Battery Backup",
      category: "IT Equipment",
      serialNumber: "UPS-2024-011",
      location: "Branch Office A",
      fieldOffice: "Branch A",
      custodian: "Mike Chen",
      status: "Available",
      condition: "Good",
      value: "$350",
      nbv: "$280",
      purchaseDate: "2024-01-20",
      poNumber: "PO-2024-002",
      supplier: "APC",
      lastInspection: "2026-01-25",
    },
  ];

export const AVAILABLE_FIELDS: ReportFieldDefinition[] = [
  { id: 'assetId', label: 'Asset ID', sensitive: false },
  { id: 'name', label: 'Asset Name', sensitive: false },
  { id: 'category', label: 'Category', sensitive: false },
  { id: 'serialNumber', label: 'Serial Number', sensitive: false },
  { id: 'epc', label: 'EPC/RFID Tag', sensitive: false },
  { id: 'location', label: 'Location', sensitive: false },
  { id: 'fieldOffice', label: 'Field Office', sensitive: false },
  { id: 'custodian', label: 'Custodian', sensitive: false },
  { id: 'status', label: 'Status', sensitive: false },
  { id: 'condition', label: 'Condition', sensitive: false },
  { id: 'value', label: 'Value', sensitive: true },
  { id: 'nbv', label: 'Net Book Value', sensitive: true },
  { id: 'purchaseDate', label: 'Purchase Date', sensitive: false },
  { id: 'poNumber', label: 'PO Number', sensitive: true },
  { id: 'supplier', label: 'Supplier', sensitive: false },
  { id: 'lastInspection', label: 'Last Inspection', sensitive: false },
]

export const PREDEFINED_REPORTS: Omit<PredefinedReport, 'icon'>[] = [
  {
    id: 'asset-register-location',
    name: 'Asset Register by Location',
    description: 'Complete asset inventory grouped by physical location',
    category: 'Asset Register',
    accessLevel: 'all',
  },
  {
    id: 'asset-register-field-office',
    name: 'Asset Register by Field Office',
    description: 'Asset inventory organized per field office',
    category: 'Asset Register',
    accessLevel: 'all',
  },
  {
    id: 'asset-register-custodian',
    name: 'Asset Register by Custodian',
    description: 'Asset assignments per employee/department',
    category: 'Asset Register',
    accessLevel: 'manager',
  },
  {
    id: 'lifecycle-summary',
    name: 'Lifecycle Status Summary',
    description: 'Asset distribution across lifecycle stages (registered, in-use, retired, damaged, disposed)',
    category: 'Lifecycle',
    accessLevel: 'all',
  },
  {
    id: 'disposal-summary',
    name: 'Disposal Summary Report',
    description: 'Disposal history by method, value, and time period',
    category: 'Disposal',
    accessLevel: 'manager',
  },
  {
    id: 'transfer-history',
    name: 'Transfer History Report',
    description: 'Asset movement tracking per asset or department',
    category: 'Transfer',
    accessLevel: 'all',
  },
]

export const SEED_SAVED_QUERIES: SavedQuery[] = [
  {
    id: 'SQ-001',
    name: 'High-Value IT Assets',
    description: 'IT equipment valued over $1000',
    filters: [
      { field: 'category', operator: 'equals', value: 'IT Equipment' },
      { field: 'value', operator: 'greater_than', value: '1000' },
    ],
    selectedFields: ['assetId', 'name', 'serialNumber', 'value', 'location'],
    groupBy: 'location',
    sortBy: 'value',
    sortOrder: 'desc',
    createdBy: 'admin@company.com',
    createdAt: '2024-01-15',
  },
  {
    id: 'SQ-002',
    name: 'Retired Assets - Q1 2024',
    description: 'All assets retired in Q1',
    filters: [
      { field: 'status', operator: 'equals', value: 'Retired' },
      { field: 'retirementDate', operator: 'between', value: '2024-01-01,2024-03-31' },
    ],
    selectedFields: ['assetId', 'name', 'retirementDate', 'retirementReason', 'value'],
    groupBy: 'none',
    sortBy: 'retirementDate',
    sortOrder: 'desc',
    createdBy: 'manager@company.com',
    createdAt: '2024-01-20',
  },
]

export const SEED_SCHEDULED_REPORTS: ScheduledReport[] = [
  {
    id: 'SR-001',
    name: 'Monthly Asset Register Report',
    reportType: 'asset-register-location',
    frequency: 'monthly',
    recipients: ['operations@company.com', 'admin@company.com'],
    format: 'pdf',
    nextRun: '2026-03-01',
    lastRun: '2026-02-01',
    enabled: true,
    createdBy: 'admin@company.com',
  },
  {
    id: 'SR-002',
    name: 'Weekly Asset Movement Summary',
    reportType: 'transfer-history',
    frequency: 'weekly',
    recipients: ['operations@company.com'],
    format: 'excel',
    nextRun: '2026-03-03',
    lastRun: '2026-02-24',
    enabled: true,
    createdBy: 'admin@company.com',
  },
  {
    id: 'SR-003',
    name: 'Quarterly Disposal Review',
    reportType: 'disposal-summary',
    frequency: 'quarterly',
    recipients: ['finance@company.com', 'admin@company.com'],
    format: 'excel',
    nextRun: '2026-04-01',
    lastRun: '2026-01-01',
    enabled: false,
    createdBy: 'admin@company.com',
  },
]

export function resolveOfficeMetrics(fieldOffice: string): OfficeMetrics {
  return OFFICE_DATA[fieldOffice] ?? OFFICE_DATA['All Offices']
}

export function filterPendingActions(fieldOffice: string): PendingAction[] {
  if (fieldOffice === 'All Offices') return ALL_PENDING_ACTIONS
  return ALL_PENDING_ACTIONS.filter((action) => action.fieldOffice === fieldOffice)
}

export function resolveComplianceGaps(fieldOffice: string): ComplianceGap[] {
  return resolveOfficeMetrics(fieldOffice).complianceGaps
}
